# version: '3'

 
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    ports:
      - ":80"
    depends_on:
      - app
    container_name: nginx-${APP_NAME}

  
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app-${APP_NAME}

  db:
    image: mysql:8.0
    container_name: db-${APP_NAME}
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
       MYSQL_DATABASE: laradocker
       MYSQL_ROOT_PASSWORD: root
    ports:
      - ":80"
    networks:
     back:
        ipv4_address: ${DB_HOST}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  
  PhpMyAdmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: myadmin-${APP_NAME}
    ports:
      - ":80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

networks:
#Internal-only network for proper nginx proxying and ssh
  back:
    driver: bridge
    enable_ipv6: true
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 173.19.0.0/24
       
 


 
   
